mvc/MVC/MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC.Domain.Repository;
using MVC.Models;

namespace MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly DataManager _dataManager;

    public HomeController(ILogger<HomeController> logger, DataManager dataManager)
    {
        _logger = logger;
        _dataManager = dataManager;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult ShowWorkers()
    {
        return View(_dataManager.worker.GetAllWorkers());
    }

    public IActionResult ShowProjects(string name, uint? priority = null, Project.SortState sortOrder = Project.SortState.NameAsc)
    {
        Console.WriteLine(name);
        Console.WriteLine(priority);
        Console.WriteLine(sortOrder);
        var projects = _dataManager.project.GetAllProjects();
        //фильтрация
        if (!String.IsNullOrEmpty(name))
        {
            projects = projects.Where(p => p.name.Contains(name));
        }
        if (priority != null && priority != 0)
        {
            projects = projects.Where(p => p.priority == priority);
        }
        // ViewBag.NameSort = sortOrder==Project.SortState.NameAsc ? Project.SortState.NameDesc : Project.SortState.NameAsc;
        // ViewBag.PrioritySort = sortOrder == Project.SortState.PriorityAsc ? Project.SortState.PriorityDesc : Project.SortState.PriorityAsc;
        // сортировка
        projects = sortOrder switch
        {
            Project.SortState.NameDesc => projects.OrderByDescending(s => s.name),
            Project.SortState.PriorityAsc => projects.OrderBy(s => s.priority),
            Project.SortState.PriorityDesc => projects.OrderByDescending(s => s.priority),
            _ => projects.OrderBy(s => s.name),
        };
        
        var viewModel = new IndexViewModel
        {
            FilterViewModel = new FilterViewModel(name, priority),
            SortViewModel = new SortViewModel(sortOrder),
            Projects = projects
        };

        return View(viewModel);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

mvc/MVC/MVC/Controllers/ProjectController.cs
using System.ComponentModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC.Domain.Repository;
using MVC.Models;

namespace MVC.Controllers;

public class ProjectController : Controller
{
    private readonly DataManager dataManager;

    public ProjectController(DataManager dataManager)
    {
        this.dataManager = dataManager;
    }

    public IActionResult Edit(Guid id)
    {
        var entity = id == default ? new Project() : dataManager.project.GetProjectById(id);
        ViewBag.workers = new SelectList(dataManager.worker.GetAllWorkers(), nameof(Worker.id), nameof(Worker.name));
        return View(entity);
    }

    private void UnbindProject(Guid id)
    {
        var allWorkers = dataManager.worker.GetAllWorkers();
        foreach (var currWorker in allWorkers)
        {
            currWorker.projects?.Remove(id);
            dataManager.worker.MakeWorkerModified(currWorker);
        }

        dataManager.worker.SaveChanges();
    }

    private void BindProjectToWorker(Project model)
    {
        if (model.workers.Contains(default) && model.workers.Count == 1)
        {
            UnbindProject(model.id);
            return;
        }
        var allWorkers = dataManager.worker.GetAllWorkers();
        foreach (var currentWorker in allWorkers)
        {
            currentWorker.projects ??= new List<Guid>();

            if (!model.workers.Contains(currentWorker.id))
            {
                currentWorker.projects.Remove(model.id);
                dataManager.worker.MakeWorkerModified(currentWorker);
                continue;
            }

            var uniqueProjects = new HashSet<Guid>(currentWorker.projects);
            uniqueProjects.Add(model.id);
            currentWorker.projects = new List<Guid>(uniqueProjects);
            dataManager.worker.MakeWorkerModified(currentWorker);
        }
        dataManager.worker.SaveChanges();
    }

    [HttpPost]
    public IActionResult Edit(Project model)
    {
        if (ModelState.IsValid)
        {
            BindProjectToWorker(model);
            dataManager.project.SaveProject(model);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
        }

        ViewBag.workers = new SelectList(dataManager.worker.GetAllWorkers(), nameof(Worker.id), nameof(Worker.name));
        return View(model);
    }

    [HttpPost]
    public IActionResult Delete(Guid id)
    {
        dataManager.project.DeleteProject(id);
        return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
    }
}

mvc/MVC/MVC/Controllers/ProjectItemController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Domain.Repository;
using MVC.Models;

namespace MVC.Controllers;

public class ProjectItemController : Controller
{
    private readonly DataManager dataManager;

    public ProjectItemController(DataManager dataManager)
    {
        this.dataManager = dataManager;
    }

    public IActionResult Index(Guid id)
    {
        if (id != default)
        {
            var project = dataManager.project.GetProjectById(id);
            var workers = new List<Worker>();
            if (project.workers != null)
            {
                workers.AddRange(from worker in project.workers where worker != default select dataManager.worker.GetWorkerById(worker));
            }

            project.director = dataManager.worker.GetWorkerById(project.directorId);
            ViewBag.workers = workers;
            return View("Show", project);
        }

        return View(dataManager.project.GetAllProjects());
    }
}

mvc/MVC/MVC/Controllers/WorkerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVC.Domain.Repository;
using MVC.Models;

namespace MVC.Controllers;

public class WorkerController : Controller
{
    private readonly DataManager dataManager;

    public WorkerController(DataManager dataManager)
    {
        this.dataManager = dataManager;
    }

    public IActionResult Edit(Guid id)
    {
        var entity = id == default ? new Worker() : dataManager.worker.GetWorkerById(id);
        return View(entity);
    }

    [HttpPost]
    public IActionResult Edit(Worker model)
    {
        if (ModelState.IsValid)
        {
            dataManager.worker.SaveWorker(model);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
        }
        return View(model);
    }

    [HttpPost]
    public IActionResult Delete(Guid id)
    {
        dataManager.worker.DeleteWorker(id);
        return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).Replace("Controller", ""));
    }
}

mvc/MVC/MVC/Controllers/WorkerItemController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Domain.Repository;
using MVC.Models;

namespace MVC.Controllers;

public class WorkerItemController : Controller
{
    private readonly DataManager dataManager;

    public WorkerItemController(DataManager dataManager)
    {
        this.dataManager = dataManager;
    }

    public IActionResult Index(Guid id)
    {
        if (id != default)
        {
            var worker = dataManager.worker.GetWorkerById(id);
            var projects = new List<Project>();
            if (worker.projects != null)
            {
                projects.AddRange(worker.projects.Select(project => dataManager.project.GetProjectById(project)));
            }

            ViewBag.projects = projects;
            return View("Show", worker);
        }

        return View(dataManager.worker.GetAllWorkers());
    }
}

mvc/MVC/MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mvc/MVC/MVC/Views/Home/ShowProjects.cshtml
@model IndexViewModel
@{
    ViewData["Title"] = "Show projects";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <div class="div-box">
        <a asp-controller="Project" asp-action="Edit">Добавить проект</a>
    </div>
    <form method="get">
        <div class="form-inline">
            <label>Имя: </label>
            <input name="name" value="@Model.FilterViewModel.SelectedName" class="form-control"/>

            <label>Приоритет: </label>
            <input name="priority" type="number" min="1" value="@Model.FilterViewModel.SelectedPriority" class="form-control"/>

            <input type="submit" value="Фильтр" class="btn btn-outline-dark"/>
        </div>
    </form>
    <table class="table">
        <thead>Сортировка</thead>
        <tr>
            <th>
                <a
                    asp-action="ShowProjects" 
                    asp-route-sortOrder="@(Model.SortViewModel.NameSort)"
                    asp-route-name="@(Model.FilterViewModel.SelectedName)"
                    asp-route-priority="@(Model.FilterViewModel.SelectedPriority)">
                    Имя
                </a>
            </th>
            <th>
                <a
                    asp-action="ShowProjects"
                    asp-route-sortOrder="@(Model.SortViewModel.PrioritySort)"
                    asp-route-name="@(Model.FilterViewModel.SelectedName)"
                    asp-route-priority="@(Model.FilterViewModel.SelectedPriority)">
                    Приоритет
                </a>
            </th>
        </tr>
    </table>
    @if (Model.Projects.Any())
    {
        <div>
            @foreach (var entity in Model.Projects)
            {
                <div>
                    <a asp-controller="Project" asp-action="Edit" asp-route-id="@entity.id">редактировать</a>
                    |
                    <form style="display: inline-block;" id="form-@entity.id" asp-controller="Project" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@entity.id">
                        <a href="#" onclick="document.getElementById('form-@entity.id').submit();">удалить</a>
                    </form>
                    |
                    <a asp-controller="ProjectItem" asp-action="Index" asp-route-id="@entity.id">
                        @($"{entity.name}")
                    </a>
                </div>
            }
        </div>
    }
</div>

mvc/MVC/MVC/Views/Home/ShowWorkers.cshtml
@model IQueryable<Worker>
@{
    ViewData["Title"] = "Show workers";
}
<div>
    <h1>@ViewData["Title"]</h1>
    <div class="div-box">
        <a asp-controller="Worker" asp-action="Edit">Добавить работника</a>
    </div>
    @if (Model.Any())
    {
        <div>
            @foreach (var entity in Model)
            {
                <div>
                    <a asp-controller="Worker" asp-action="Edit" asp-route-id="@entity.id">редактировать</a>
                    |
                    <form style="display: inline-block;" id="form-@entity.id" asp-controller="Worker" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@entity.id">
                        <a href="#" onclick="document.getElementById('form-@entity.id').submit();">удалить</a>
                    </form>
                    |
                    <a asp-controller="WorkerItem" asp-action="Index" asp-route-id="@entity.id">
                        @($"{entity.name} ${entity.lastName}")
                    </a>
                </div>
            }
        </div>
    }
</div>